### ISSUE TITLE
Nice work! May I ask when the code and paper will be available?

### ISSUE THREAD

**Issue by youcaiSUN** [nku-zhichengzhang/MART#1]

**Comment by nku-zhichengzhang** [comment]
Thank you, we are preparing a clear camera-ready version and it will be soon (possibly in the middle of April).

**Comment by YCHuang2112sub** [comment]
Excuse me, where can I get videomae_base_patch16_224.pth. Did you finetuned the videomae_base model or do you use the official one. Since the currently uploaded one is 0 byte.

**Comment by nku-zhichengzhang** [comment]
Yes, just place the downloaded ckpt of videomae at there.
